# -*- coding: utf-8 -*-
"""face_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E6cgFicbguEgT2HO1VWp0si62br3ePtQ
"""

import matplotlib.pyplot as plt
import matplotlib.image as ming
import numpy as np
samp=8
n=['hannah','claudia','elezi','martha','cristi']
train_data=np.zeros((40,107*110*3))
train_label=np.zeros((40))
count=-1
plt.figure()
plt.ion()

for i in range(1,6):
  for j in range(1,9):
    plt.cla()
    count=count+1
    #print count
    path='/content/drive/My Drive/photo /train/u%d/%d.png'%(i,j)
    im=ming.imread(path)
    feat=im.reshape(1,-1)
    train_data[count,:]=feat
    train_label[count]=i

    plt.imshow(im,cmap='gray')
    plt.title('user num.'+str(i)+':name : '+n[i-1]+' : '+str(j))
    plt.pause(0.1)

test_data=np.zeros((5,107*110*3))
test_label=np.zeros(5)
count=-1
n=['hannah','claudia','elezi','martha','cristi']
for i in range(1,6):
    #plt.cla()
    count=count+1
    #print count
    path='/content/drive/My Drive/photo /test/%d.png'%(i)
    im=ming.imread(path)
    feat=im.reshape(1,-1)
    test_data[count,:]=feat
    test_label[count]=i

    plt.imshow(im,cmap='gray')
    plt.title('user num.'+str(i)+':: name : '+n[i-1])
    plt.pause(0.2)

test_data=np.zeros((1,107*110*3))
test_label=np.zeros(1)


a=int(input("Enter the number to select the image you want to test (choose only from 1 to 5) :: "))

count=-1
for i in range(a,a+1):
  path='/content/drive/My Drive/photo /test/%d.png'%i
  im=ming.imread(path)
  feat=im.reshape(1,-1)
  test_data[count,:]=feat
  test_label[count]=i

  plt.imshow(im,cmap='Blues')
  plt.title('The Test Image')

for i in range(0,1):
  test_sample=test_data[i,:]
  actual_label=test_label[i]

  d=np.zeros((40))

  for j in range(0,40):
    d[j]=np.sum((test_sample-train_data[j,:])**2)

  val=d.min()
  ind=d.argmin()
plt.imshow(im,cmap='gray')
if ind in np.arange(0,8):
  print('this picture belongs to hannah')
if ind in np.arange(9,18):
  print('this picture belongs to claudia')
if ind in np.arange(19,27):
  print('this picture belongs to elezi')
if ind in np.arange(28,36):
  print('this picture belongs to martha')
if ind in np.arange(37,45):
  print('this picture belongs to cristi')

1